DROP TABLE user_roles
IF EXISTS;
DROP TABLE users
IF EXISTS;
DROP TABLE cards
IF EXISTS;
DROP TABLE columns
IF EXISTS;
DROP SEQUENCE global_seq
IF EXISTS;

CREATE SEQUENCE global_seq
  AS INTEGER
  START WITH 100000;

CREATE TABLE users
(
  id         INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name       VARCHAR(255)               NOT NULL,
  email      VARCHAR(255)               NOT NULL,
  password   VARCHAR(255)               NOT NULL,
  registered TIMESTAMP DEFAULT now()    NOT NULL,
  enabled    BOOLEAN DEFAULT TRUE       NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx
  ON USERS (email);

CREATE TABLE user_roles
(
  user_id INTEGER NOT NULL,
  role    VARCHAR(255),
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES users (id)
    ON DELETE CASCADE
);

CREATE TABLE columns (
  id           INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name         VARCHAR(255) NOT NULL,
  description  VARCHAR(255)
);
CREATE UNIQUE INDEX columns_unique_name_idx
  ON columns (name);

CREATE TABLE cards
(
  id           INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name         VARCHAR(255) NOT NULL,
  description  VARCHAR(255),
  column_id    INTEGER NOT NULL,
  FOREIGN KEY (column_id) REFERENCES columns (id)
    ON DELETE CASCADE
);

CREATE UNIQUE INDEX cards_unique_name_idx
  ON cards (name);

